languageCode = "en-us"
title = "Coleman-Derr Lab"
baseurl = "http://example.org/"
SectionPagesMenu = "main"

paginate = 5
canonifyurls = true

[params]
  description = "this is my description"
  cover = "images/cover.jpg"
  author = "Devin!"
  authorlocation = "Kensington"
  bio= "born on the mississippi river"
  logo = "images/logo.jpg"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "dcolemanderr"
  twitterName = "DevinColemanDer"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "DevinColemanDer"

[taxonomies]
  category = "categories"
  tag = "tags"

